config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lectures, only: [:index, :new, :create]
  #resource :account, :controller => "users"
  resources :users, only: [:index, :new, :create]
  get '/reset_password', to: 'users#reset_password', as: :reset_password
  patch '/reset_password', to: 'users#reset_password'

  #resource :user_sessions, only: [:create]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  post '/sign_in', to: 'user_sessions#create'

  resources :grades, only: [:new, :create, :index, :edit, :update]

  post '/reports', to: 'reports#create'

  root to: "welcome#index"
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_one_attached :submission
  belongs_to :lecture
  belongs_to :student
  validates_numericality_of :grade , :less_than_or_equal_to=>100, :greater_than_or_equal_to=>0, :allow_nil => true
  validates :lecture, presence: true
  validates :student, presence: true
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def new
      @grade = Grade.new
    if logged_in_as_admin
      render :new_admin
    elsif logged_in_as_lecturer
      render :new_lecturer
    elsif logged_in_as_student
      render :new_student
    else
      kick_out
    end
  end

  def index
    if logged_in_as_admin
      @grades = Grade.all
      render :index_admin
    elsif logged_in_as_lecturer
      @grades = Grade.all
      render :index_lecturer
    elsif logged_in_as_student
      if params[:lecturer]
        @grades = Grade.joins(lecture: :lecturer).where("grades.student_id = #{current_user.id.to_s} AND users.login LIKE '%#{params[:lecturer]}%'")
      else
        @grades = Grade.where(:student_id => current_user.id)
      end
      render :index_student
    else
      kick_out
    end
  end

  def create
    if logged_in_as_admin
      @grade = Grade.new(params.require(:grade).permit(:student_id, :lecture_id, :grade, :comment))
      if @grade.save
        flash[:success] = "Grade created!"
        redirect_to grades_path
      else
        render :new_admin
      end
    elsif logged_in_as_lecturer
      @grade = Grade.new(params.require(:grade).permit(:student_id, :lecture_id, :grade))
      if @grade.save
        flash[:success] = "Grade created!"
        redirect_to grades_path
      else
        render :new_lecturer
      end
    elsif logged_in_as_student
      grade_params = params.require(:grade).permit(:lecture_id, :submission)
      grade_params[:student_id] = current_user.id
      @grade = Grade.new(grade_params)
      if @grade.save
        flash[:success] = "Report submitted!"
        redirect_to grades_path
      else
        render :new_student
      end
    else
      kick_out
    end
  end
 
  def edit
    if logged_in_as_admin
      @grade = Grade.find(params[:id])
      render :edit_admin
    elsif logged_in_as_lecturer
      @grade = Grade.find(params[:id])
      if Lecturer.find(current_user.id).lectures.include? @grade.lecture 
        render :edit_lecturer
      else
        kick_out
      end
    elsif logged_in_as_student
      @grade = Grade.find(params[:id])
      if @grade.student != Student.find(current_user.id)
        kick_out
      else
        render :edit_student
      end
    else
      kick_out
    end
  end

  def update
    if logged_in_as_admin
      @grade = Grade.find(params[:id])
      if @grade.update(params.require(:grade).permit(:student_id, :lecture_id, :grade, :comment, :submission)) and @grade.submission.attach(params[:submission])
        flash[:success] = "Update successful!"
        redirect_to grades_path
      else
        render :edit_admin
      end
    elsif logged_in_as_lecturer
      @grade = Grade.find(params[:id])
      if @grade.update(params.require(:grade).permit(:grade))
        flash[:success] = "Update successful!"
        redirect_to grades_path
      else
        render :edit_lecturer
      end
    elsif logged_in_as_student
      @grade = Grade.find(params[:id])
      if @grade.student != Student.find(current_user.id)
        kick_out
      else
        if @grade.update(params.require(:grade).permit(:comment, :submission))
          flash[:success] = "Update successful!"
          redirect_to grades_path
        else
          render :edit_student
        end
      end
    else
      kick_out
    end
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/edit_admin.html.erb
<%= form_for @grade, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @grade %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :lecture %></div>
    <div class="w3-rest"><%= f.select(:lecture_id, Lecture.all.collect {|p| [ p.name, p.id ] }) %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :student %></div>
    <div class="w3-rest"><%= f.select(:student_id, User.where(role: "student").collect {|p| [ p.login, p.id ] }) %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :grade %></div>
    <div class="w3-rest"><%= f.number_field :grade, class: "w3-input", style: "width: 80px" %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :comment %></div>
    <div class="w3-rest"><%= f.text_area :comment, class: "w3-input w3-border", style: "min-height: 150px; padding-left: 0" %></div>
  </div>
  <div class="w3-center">
    <%= f.submit class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>

app/views/grades/edit_lecturer.html.erb
<%= form_for @grade, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @grade %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :lecture %></div>
    <div class="w3-rest"><%= @grade.lecture.name %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :student %></div>
    <div class="w3-rest"><%= @grade.student.login %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :grade %></div>
    <div class="w3-rest"><%= f.number_field :grade, class: "w3-input", style: "width: 80px" %></div>
  </div>
  <div class="w3-center">
    <%= f.submit class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>

app/views/grades/edit_student.html.erb
<%= form_for @grade, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @grade %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :lecture %></div>
    <div class="w3-rest"><%= @grade.lecture.name %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :grade %></div>
    <div class="w3-rest"><%= @grade.grade %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :comment %></div>
    <div class="w3-rest"><%= f.text_area :comment, class: "w3-input w3-border", style: "min-height: 150px; padding-left: 0" %></div>
  </div>

  <div class="w3-center">
  <%= f.submit class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>

app/views/grades/index_admin.html.erb
<table class="w3-table w3-striped w3-bordered">
  <tr>
    <th>Lecturer</th>
    <th>Lecture</th>
    <th>Student</th>
    <th>Grade</th>
    <th>Submission</th>
    <th>Comment</th>
    <th>Action</th>
  </tr>
 
  <% @grades.each do |grade| %>
    <tr>
      <td><%= grade.lecture.lecturer.login %></td>
      <td><%= grade.lecture.name %></td>
      <td><%= grade.student.login %></td>
      <td><%= grade.grade %></td>
      <td>
      <% if grade.submission.attached? %>
        <%= link_to grade.submission.filename.to_s, rails_blob_url(grade.submission, disposition: "attachment") %>
      <% end %>
      </td>
      <td>
      <% if grade.comment %>
        <%= grade.comment.html_safe %>
      <% end %>
      </td>
        <td><%= link_to 'Edit', edit_grade_path(grade), :class => "w3-button w3-light-blue" %></td>
    </tr>
  <% end %>
</table>

<div class="w3-center w3-margin">
  <%= link_to 'New Grade', new_grade_path, :class => "w3-button w3-light-blue" %>
</div>

app/views/grades/index_lecturer.html.erb
<table class="w3-table w3-striped w3-bordered">
  <tr>
    <th>Lecturer</th>
    <th>Lecture</th>
    <th>Student</th>
    <th>Grade</th>
    <th>Submission</th>
    <th>Comment</th>
    <th>Action</th>
  </tr>
 
  <% @grades.each do |grade| %>
    <tr>
      <td><%= grade.lecture.lecturer.login %></td>
      <td><%= grade.lecture.name %></td>
      <td><%= grade.student.login %></td>
      <td><%= grade.grade %></td>
      <td>
      <% if grade.submission.attached? %>
        <%= link_to grade.submission.filename.to_s, rails_blob_url(grade.submission, disposition: "attachment") %>
      <% end %>
      </td>
      <td>
      <% if grade.comment %>
        <%= grade.comment.html_safe %>
      <% end %>
      </td>
      <% if grade.lecture.lecturer_id == current_user.id %>
        <td><%= link_to 'Edit', edit_grade_path(grade), :class => "w3-button w3-light-blue" %></td>
      <% else %>
        <td><a class="w3-button w3-disabled">Edit</a></td>
      <% end %>
    </tr>
  <% end %>
</table>

<div class="w3-center w3-margin">
  <%= link_to 'New Grade', new_grade_path, :class => "w3-button w3-light-blue" %>
</div>

app/views/grades/index_student.html.erb
<p data-search-info></p>

<table class="w3-table w3-striped w3-bordered" style="margin: auto">
  <tr>
    <th>Lecturer</th>
    <th>Lecture</th>
    <th>Grade</th>
    <th>Submission</th>
    <th>Comment</th>
  </tr>
 
  <% @grades.each do |grade| %>
    <tr>
      <td><%= grade.lecture.lecturer.login %></td>
      <td><%= grade.lecture.name %></td>
      <td><%= grade.grade %></td>
      <td>
      <% if grade.submission.attached? %>
        <%= link_to grade.submission.filename.to_s, rails_blob_url(grade.submission, disposition: "attachment") %>
      <% end %>
      </td>
      <td>
      <% if grade.comment %>
        <%= grade.comment.html_safe %>
      <% end %>
      </td>
      <td><%= link_to 'Comment', edit_grade_path(grade), :class => "w3-button w3-light-blue" %></td>
    </tr>
  <% end %>
</table>

<div class="w3-center">
  <%= link_to "Generate Report", {controller: "reports", action: "create"}, :method => :post, :class => "w3-button w3-light-blue" %>
</div>

<%= form_tag(grades_url, method: "get", class: "w3-margin") do %>
  <div class="w3-right" style="width: 10%">
  <%= submit_tag("Filter", class: "w3-button w3-light-blue") %>
  </div>
  <%= text_field_tag(:lecturer, "", class: "w3-input w3-border w3-round", placeholder: "Filter by lecturer...", style: "width: 90%") %>
<% end %>

<div class="w3-center w3-margin">
  <%= link_to 'New Submission', new_grade_path, :class => "w3-button w3-light-blue" %>
</div>

app/views/grades/new_admin.html.erb
<%= form_for @grade, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @grade %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :lecture %></div>
    <div class="w3-rest"><%= f.select(:lecture_id, Lecture.all.collect {|p| [ p.name, p.id ] }) %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :student %></div>
    <div class="w3-rest"><%= f.select(:student_id, User.where(role: "student").collect {|p| [ p.login, p.id ] }) %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :grade %></div>
    <div class="w3-rest"><%= f.number_field :grade, class: "w3-input", style: "width: 80px" %></div>
  </div>
  <div class="w3-center">
    <%= f.submit class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>

app/views/grades/new_lecturer.html.erb
<%= form_for @grade, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @grade %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :lecture %></div>
    <div class="w3-rest"><%= f.select(:lecture_id, Lecture.where(:lecturer => current_user).collect {|p| [ p.name, p.id ] }) %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :student %></div>
    <div class="w3-rest"><%= f.select(:student_id, User.where(role: "student").collect {|p| [ p.login, p.id ] }) %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :grade %></div>
    <div class="w3-rest"><%= f.number_field :grade, class: "w3-input", style: "width: 80px" %></div>
  </div>
  <div class="w3-center">
    <%= f.submit class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>

app/views/grades/new_student.html.erb
<%= form_for @grade, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @grade %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :lecture %></div>
    <div class="w3-rest"><%= f.select(:lecture_id, Lecture.all.collect {|p| [ p.name, p.id ] }) %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :submission %></div>
    <div class="w3-rest">
      <% if @grade.submission.attached? %>
        <%= link_to @grade.submission.filename.to_s, rails_blob_url(@grade.submission, disposition: "attachment") %>
        <br>
      <% end %>
      <%= f.file_field :submission ,:onchange => "validate_file(this);", :data => { :allowed_extension => "pdf", :max_file_size => 500.kilobytes } %>
      <br>
      (Maximal 500 kB, only pdf files)
    </div>
  </div>
  <div class="w3-center">
    <%= f.submit "Submit", class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>