config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lectures, only: [:index, :new, :create]
  #resource :account, :controller => "users"
  resources :users, only: [:index, :new, :create]
  get '/reset_password', to: 'users#reset_password', as: :reset_password
  patch '/reset_password', to: 'users#reset_password'

  #resource :user_sessions, only: [:create]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  post '/sign_in', to: 'user_sessions#create'

  resources :grades, only: [:new, :create, :index, :edit, :update]

  post '/reports', to: 'reports#create'

  root to: "welcome#index"
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :lecturer
  has_many :grades, dependent: :destroy
  validates :lecturer, presence: true
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def new
    if logged_in_as_admin
      @lecture = Lecture.new
      render :new_admin
    elsif logged_in_as_lecturer
      @lecture = Lecture.new
      render :new_lecturer
    else
      kick_out
    end
  end

  def index
    if logged_in_as_admin or logged_in_as_lecturer
      @lectures = Lecture.all
    else
      kick_out
    end
  end

  def create
    if logged_in_as_admin
      @lecture = Lecture.new(params.require(:lecture).permit(:name, :lecturer_id))
      if @lecture.save
        flash[:success] = "Lecture created!"
        redirect_to lectures_path
      else
        render :new_admin
      end
    elsif logged_in_as_lecturer
      @lecture = Lecture.new(params.require(:lecture).permit(:name))
      @lecture.lecturer = Lecturer.find(current_user.id)
      if @lecture.save
        flash[:success] = "Lecture created!"
        redirect_to lectures_path
      else
        render :new_admin
      end
    else
      kick_out
    end
  end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/index.html.erb
<table class="w3-table w3-striped w3-bordered">
  <tr>
    <th>Name</th>
    <th>Lecturer</th>
  </tr>
 
  <% @lectures.each do |lecture| %>
    <tr>
      <td><%= lecture.name %></td>
      <td><%= lecture.lecturer.login %></td>
    </tr>
  <% end %>
</table>

<div class="w3-center w3-margin">
  <%= link_to 'New Lecture', new_lecture_path, :class => "w3-button w3-light-blue" %>
</div>

app/views/lectures/new_admin.html.erb
<%= form_for @lecture, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @lecture %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :name %></div>
    <div class="w3-rest"><%= f.text_field :name %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :lecturer %></div>
    <div class="w3-rest"><%= f.select(:lecturer_id, User.where(:role => "lecturer").collect {|p| [ p.login, p.id ] }) %></div>
  </div>
  <div class="w3-center">
    <%= f.submit class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>

app/views/lectures/new_lecturer.html.erb
<%= form_for @lecture, :html => {:class => "w3-container w3-card-4 w3-margin"} do |f| %>
  <%= render 'shared/errors', object: @lecture %>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :name %></div>
    <div class="w3-rest"><%= f.text_field :name %></div>
  </div>
  <div class="w3-center">
    <%= f.submit class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>