config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lectures, only: [:index, :new, :create]
  #resource :account, :controller => "users"
  resources :users, only: [:index, :new, :create]
  get '/reset_password', to: 'users#reset_password', as: :reset_password
  patch '/reset_password', to: 'users#reset_password'

  #resource :user_sessions, only: [:create]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  post '/sign_in', to: 'user_sessions#create'

  resources :grades, only: [:new, :create, :index, :edit, :update]

  post '/reports', to: 'reports#create'

  root to: "welcome#index"
end

app/models/user.rb
class User < ApplicationRecord
  validates :role, inclusion: { in: ["admin", "lecturer", "student"], message: "%{value} is not a valid role" }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if logged_in_as_admin
      @users = User.all
      render :index_admin
    elsif logged_in_as_lecturer
      @users = User.where(:role => "student")
      render :index_lecturer
    else
      flash[:error] = "You do not have access to this site."
      redirect_to root_url
    end
  end

  def new
    if logged_in_as_admin or logged_in_as_lecturer
      @user = User.new
    else
      flash[:error] = "You do not have access to this site."
      redirect_to root_url
    end
  end

  def create
    if logged_in_as_admin
      @user = User.new(:login => users_params[:login], :role => users_params[:role], :password => Digest::MD5.hexdigest(users_params[:password]))
      if users_params[:password] == users_params[:password_confirmation] and @user.save
        flash[:success] = "Account registered!"
        redirect_to root_path
      else
        render :new
      end
    elsif logged_in_as_lecturer
      @user = User.new(:login => users_params[:login], :role => users_params[:role], :password => Digest::MD5.hexdigest(users_params[:password]))
      if users_params[:password] == users_params[:password_confirmation] and @user.save
        flash[:success] = "Account registered!"
        redirect_to root_path
      else
        render :new
      end
    else
      flash[:error] = "You do not have access to this site."
      redirect_to root_url
    end
  end

  def reset_password
    if params[:user]
      @user = User.find_by params[:user].permit(:login, :secret_answer)
      if @user
        if params[:user][:password] == params[:user][:password_confirmation]
          @user.update(:password => Digest::MD5.hexdigest(params[:user][:password]))
          @user.save
          flash[:success] = "Password changed successfully!"
          redirect_to root_url
        else
          flash[:error] = "Passwords don't match!"
          render :reset_password_for_user
        end
      else
        flash[:error] = "Wrong answer!"
        @user = User.find_by :login => params[:user][:login]
        render :reset_password_for_user
      end
    elsif params[:login]
      @user = User.find_by(:login => params[:login])
      if @user and @user.secret_question
        render :reset_password_for_user
      else
        flash[:error] = "This user does not exist or have a secret answer set!"
        redirect_to reset_password_url
      end
    else
      @user = User.new
      render :reset_password
    end
  end

private
  def users_params
    params.require(:user).permit(:login, :role, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index_admin.html.erb
<table class="w3-table w3-striped w3-bordered">
  <tr>
    <th>Name</th>
    <th>Role</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.login %></td>
      <td><%= user.role %></td>
    </tr>
  <% end %>
</table>

<div class="w3-center w3-margin">
  <%= link_to 'New User', new_user_path, :class => "w3-button w3-light-blue" %>
</div>

app/views/users/index_lecturer.html.erb
<table class="w3-table w3-striped w3-bordered">
  <tr>
    <th>Name</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.login %></td>
    </tr>
  <% end %>
</table>

<div class="w3-center w3-margin">
  <%= link_to 'New Student', new_user_path, :class => "w3-button w3-light-blue" %>
</div>

app/views/users/new.html.erb
<%= form_for @user, :html => {:class => "w3-container w3-card-4 w3-margin"}  do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :login %></div>
    <div class="w3-rest"><%= f.text_field :login %></div>
  </div>

  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :role %></div>
    <div class="w3-rest">
      <% if logged_in_as_admin %>
        <%= f.select :role, ["admin", "lecturer", "student"] %>
      <% else %>
        <%= f.select :role, [["admin", {"disabled" => "disabled"}], ["lecturer", {"disabled" => "disabled"}], "student"] %>
      <% end %>
    </div>
  </div>

  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :password %></div>
    <div class="w3-rest"><%= f.password_field :password %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 100px"><%= f.label :password_confirmation %></div>
    <div class="w3-rest"><%= f.password_field :password_confirmation %></div>
  </div>

  <div class="w3-center">
    <%= f.submit 'Register', class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>

app/views/users/reset_password.html.erb
<%= form_tag reset_password_path, :class => "w3-container w3-card-4 w3-margin-top", :style => "max-width: 320px; margin: auto", :method => :get  do |f| %>

  <p>
    <%= text_field_tag :login, nil, :class => "w3-input" %>
    <%= label_tag :login, "Username" %>
  </p>
  <p><%= submit_tag 'Next', class: "w3-button w3-amber" %></p>
<% end %>

app/views/users/reset_password_for_user.html.erb
<%= form_for @user, url: {action: "reset_password"}, :html => {:class => "w3-container w3-card-4 w3-margin"}  do |f| %>
  <%= render 'shared/errors', object: @user %>

  <%= f.hidden_field :login, value: @user.login %>

  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 200px"><%= f.label :login %></div>
    <div class="w3-rest"><%= @user.login %></div>
  </div>

  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 200px"><%= f.label :secret_question %></div>
    <div class="w3-rest"><%= @user.secret_question %></div>
  </div>

  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 200px"><%= f.label :secret_answer %></div>
    <div class="w3-rest"><%= f.password_field :secret_answer %></div>
  </div>

  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 200px"><%= f.label :password %></div>
    <div class="w3-rest"><%= f.password_field :password %></div>
  </div>
  <div class="w3-row w3-section">
    <div class="w3-col" style="width: 200px"><%= f.label :password_confirmation %></div>
    <div class="w3-rest"><%= f.password_field :password_confirmation %></div>
  </div>

  <div class="w3-center">
    <%= f.submit 'Change Password', class: "w3-button w3-light-blue w3-margin" %>
  </div>
<% end %>