config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lectures, only: [:index, :new, :create]
  #resource :account, :controller => "users"
  resources :users, only: [:index, :new, :create]
  get '/reset_password', to: 'users#reset_password', as: :reset_password
  patch '/reset_password', to: 'users#reset_password'

  #resource :user_sessions, only: [:create]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  post '/sign_in', to: 'user_sessions#create'

  resources :grades, only: [:new, :create, :index, :edit, :update]

  post '/reports', to: 'reports#create'

  root to: "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Insecure Grade Management System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="w3-bar w3-dark-grey">
      <%= link_to 'Home', root_path, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(root_path) ? " w3-black" : "") %>
      <% if current_user %>
        <% if logged_in_as_admin %>
          <%= link_to 'Grades', grades_url, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(grades_url) ? " w3-black" : "") %>
          <%= link_to 'Lectures', lectures_url, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(lectures_url) ? " w3-black" : "") %>
          <%= link_to 'Users', users_url, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(users_url) ? " w3-black" : "") %>
        <% end %>

        <% if logged_in_as_lecturer %>
          <%= link_to 'Grades', grades_url, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(grades_url) ? " w3-black" : "") %>
          <%= link_to 'Lectures', lectures_url, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(lectures_url) ? " w3-black" : "") %>
          <%= link_to 'Students', users_url, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(users_url) ? " w3-black" : "") %>
        <% end %>

        <% if logged_in_as_student %>
          <%= link_to 'Grades', grades_url, :class => "w3-bar-item w3-button w3-padding-large" + (current_page?(grades_url) ? " w3-black" : "") %>
        <% end %>



        <div class="w3-right">
          <%= current_user.login %> | <%= current_user.role %> | <%= link_to 'Logout', sign_out_path, :class => "w3-button w3-amber w3-padding-large", :method => :delete, :data => {:confirm => "Are you sure you want to logout?"} %>
        </div>
      <% else %>
        <%= link_to 'Login', sign_in_path, :class => "w3-button w3-right w3-amber w3-padding-large" %>
      <% end %>
    </div>
    <% flash.each do |key, value| %>
      <% if key == "error" %>
        <div class="w3-panel w3-red w3-display-container">
          <span class="w3-button w3-red w3-large w3-display-topright" onclick="this.parentElement.style.display='none'">x</span>
          <h3><%= value %></h3>
        </div>
      <% elsif key == "success" %>
        <div class="w3-panel w3-green w3-display-container">
          <span class="w3-button w3-green w3-large w3-display-topright" onclick="this.parentElement.style.display='none'">x</span>
          <h3><%= value %></h3>
        </div>
      <% end %>
    <% end %>
    <div class="w3-content">
      <%= yield %>
    </div>
  </body>
</html>